name: Lint shell scripts

on:
  push:
    paths:
      - '.github/workflows/lint-shell.yml'
      - '**.sh'
  pull_request:
    paths:
      - '.github/workflows/lint-shell.yml'
      - '**.sh'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Recursively lint all shell scripts in the repository
      # See: https://github.com/azohra/shell-linter/blob/latest/README.md
      - name: ShellCheck 
        uses: azohra/shell-linter@latest
